import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

export interface Phone {
  phoneNumber: string;
}

// Added Sector Interface
export interface Sector {
  id?: number;
  name: string;
  active: boolean;
}

// Updated Client Interface to support optional parameters and clientCode [1.1.2, 1.2.6]
export interface Client {
  id?: number;
  clientCode?: string; // Automatically generated by backend [1.1.2]
  name: string;
  email: string;
  description?: string;
  address?: string;
  city?: string;
  contact?: string; // Legal representative
  website?: string;
  sector?: Sector;
  sectorId?: number;
  phones?: Phone[];
}

@Injectable({
  providedIn: 'root'
})
export class ClientService {

  private apiUrl = 'http://localhost:8090/api/clients';

  constructor(private http: HttpClient) { }

  getClients(): Observable<Client[]> {
    return this.http.get<Client[]>(this.apiUrl);
  }

  getClientByPhone(phone: string): Observable<Client> {
    return this.http.get<Client>(`${this.apiUrl}/${phone}`);
  }

  createClient(client: Client): Observable<Client> {
    return this.http.post<Client>(this.apiUrl, client);
  }

  updateClient(phone: string, client: Client): Observable<Client> {
    return this.http.put<Client>(`${this.apiUrl}/${phone}`, client);
  }

  getClientReservations(phone: string): Observable<any[]> {
    return this.http.get<any[]>(`${this.apiUrl}/${phone}/reservations`);
  }

  deleteClient(phone: string): Observable<void> {
    return this.http.delete<void>(`${this.apiUrl}/${phone}`);
  }
}